### ISSUE TITLE
Gem is named aws_runas but README says to install aws-runas

### ISSUE THREAD

**Issue by et304383** [vancluever/aws-runas#12]
Hyphen vs underscore.  Please update README.

**Comment by et304383** [comment]
@vancluever is this project still active?

**Comment by vancluever** [comment]
@et304383 I still maintain this project, yes - but my time has been quite limited lately and as this has not prevented from anyone installing the gem, I had not gotten to it. I have made the correction now though.

I hate to invoke the dreaded "pull requests welcome" line here, but I think in the case of something like a minor documentation correction, it makes sense (and would be more than likely be merged a lot quicker).

Thanks!

**Comment by et304383** [comment]
Sorry. Didn't mean to offend. Wasn't sure if the project was still active. I definitely should have issued a PR.
