### ISSUE TITLE
ZSH and BASH Plugin support

### ISSUE THREAD

**Issue by lucasklaassen** [vancluever/aws-runas#13]
I'm noticing that my github branch isn't displaying within an aws_runas session. It appears plugins for ZSH aren't supported. Is this an easy fix?
<img width="778" alt="screen shot 2018-02-22 at 1 23 37 pm" src="https://user-images.githubusercontent.com/6452107/36564875-a4f3af42-17d3-11e8-97b8-b89c342d4229.png">

**Comment by vancluever** [comment]
Hey @lucasklaassen - I'll have to check - I don't use zsh myself so much and I think the RC file modification/prompt integration for it may need a bit of work. If you're curious, the RC file merge stuff is [here](https://github.com/vancluever/aws-runas/blob/master/lib/aws_runas/utils.rb#L51).

I'm kind of busy right now so it might take a bit before I'm able to have a blind look but if you know what is missing let me know and I'd be happy to work on fixing the integration!

**Comment by lucasklaassen** [comment]
@vancluever sounds good, I'll look into this in my spare time. Thanks for the quick response and thank you for this nifty cli tool!

**Comment by vancluever** [comment]
Glad you like it @lucasklaassen! :grinning:

**Comment by lucasklaassen** [comment]
@vancluever I've created a pull request for this, let me know what you think.

**Comment by vancluever** [comment]
Hey @lucasklaassen, sorry for the radio silence on this one! I've merged this for now and keep an eye out for the 0.6.0 release which will have this in! Thanks!
