### ISSUE TITLE
Feature request: refresh command

### ISSUE THREAD

**Issue by et304383** [vancluever/aws-runas#18]
It would be nice if in the context of an aws-runas shell when credentials expire if we had a refresh function or something we could call.  Rather than having to exit and then run aws-runas again.

This is obviously VERY low priority.  :)

**Comment by vancluever** [comment]
Hey @et304383, this has been requested before and it's fundamentally not possible with the current design of the tool - see #10 for more details.

The best way to get around this today is by setting an appropriate session length.

Thanks!
