### ISSUE TITLE
Feature request: batch mode

### ISSUE THREAD

**Issue by et304383** [vancluever/aws-runas#20]
I would like to be able to use aws-runas in a non interactive way.  If I have a script like this:

```
aws-runas -r myrole
aws ec2 describe-instances
```

I would like to be able to run this script to get instances from the account specified by the profile myrole.  Right now, it just stops and waits for input in the new shell.

**Comment by vancluever** [comment]
Hey @et304383, although while I think first-class support for this kind of thing would be kind of cool, I think that it might be reaching beyond the initial scope of this tool, and as such, I don't think that implementing it would be a good idea.

Keep in mind though that you actually _can_ implement something like this in the current incarnation of the script today by just passing your code through a shell command off of the command line:

```
aws-runas -r myrole sh -c 'aws ec2 describe-instances; NEXTCMD; ETC'
```

You could use whatever multi-line kind of shell syntax you needed to format this into a multi-line format easy enough too.

Thanks!

**Comment by et304383** [comment]
Thanks!  This is exactly what I wanted, but I guess I missed the help output saying you could pass a command to execute.
