### ISSUE TITLE
Trollop - replace with optimist

### ISSUE THREAD

**Issue by et304383** [vancluever/aws-runas#21]
Getting this running the tool now:

```
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
```

I think this is a community wide issue, as other projects are impacted too.

**Comment by et304383** [comment]
@vancluever any chance we can get a fix for this?

**Comment by vancluever** [comment]
Hey @et304383, sorry for the radio silence on issues for the last forever. I'll be working on clearing out the pending issues soon. I'm assuming that this deprecation warning affects the versions that optimist is locked against as well?

**Comment by et304383** [comment]
I honestly don't know the answer to that question.  I just know this is a widespread issue.  For example:

https://github.com/ManageIQ/manageiq/issues/17961
https://github.com/voxpupuli/hiera-eyaml/issues/267
https://github.com/busyloop/lolcat/issues/80
https://github.com/riemann/riemann-tools/issues/186

**Comment by vancluever** [comment]
No problem @et304383, I'll probably be working on this ASAP given the nature of the issue as well, as it's something I personally agree with I'd like my tools to reflect that. Stay tuned!
